# Generated by Django 4.2.2 on 2023-07-20 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooking_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAndDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Нравится')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Рейтинг')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking_api.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='likes',
            field=models.ManyToManyField(related_name='dishes', through='cooking_api.UserAndDishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
